[2020-03-15 16:53:51,878][Thread-1:38316][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader_tags.py", line 176, in render
    template = context.template.engine.get_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: header.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\D\demo_webpage\haima\app1\views.py", line 8, in index
    return render(request,'index.html')
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: header.html
[2020-03-15 16:54:17,901][Thread-1:39292][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader_tags.py", line 176, in render
    template = context.template.engine.get_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: header.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\D\demo_webpage\haima\app1\views.py", line 8, in index
    return render(request,'index.html')
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: header.html
[2020-03-15 16:54:48,682][Thread-1:37392][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader_tags.py", line 176, in render
    template = context.template.engine.get_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: header.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\D\demo_webpage\haima\app1\views.py", line 8, in index
    return render(request,'index.html')
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: header.html
[2020-03-15 16:55:53,292][Thread-1:26400][task_id:django.request][log.py:228][ERROR][Internal Server Error: /]
Traceback (most recent call last):
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "G:\D\demo_webpage\haima\app1\views.py", line 8, in index
    return render(request,'index.html')
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 936, in render
    bit = node.render_annotated(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\base.py", line 903, in render_annotated
    return self.render(context)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\template\defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\urls\base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "G:\D\demo_webpage\haima\venv\lib\site-packages\django\urls\resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
